### ISSUE TITLE
Simplify: Apply shared styling properties to multiple elements at once to simplify the code.

### ISSUE THREAD

**Issue by josephtkim** [karlsjohnson/prj-rev-bwfs-dasmoto#4]
It is usually a good idea to simplify code by applying shared properties to multiple elements at once, rather than repeating the shared property to each one individually. Properties such as the font-family and font-weight can be applied to the elements at once like so:

```css
h1, strong, h2 {
  font-family: Helvetica;
  font-weight: bold;
}
```
